### ISSUE TITLE
The password of the dataset

### ISSUE THREAD

**Issue by tensorboy** [Fancy-Block/ICASSP2022-Depression#1]
I'm trying to download the dataset, however, there are password of the file downloaded from one drive: https://1drv.ms/u/s!AsGVGqImbOwYhHUHcodFC3xmKZKK?e=mCT5oN. (EATD-Corpus)

**Comment by Fancy-Block** [comment]
You may send an email to the authors of the paper. Email addresses can be found on the paper uploaded to arXiv.

**Comment by Fancy-Block** [comment]
You may send an email to the authors of the paper. Email addresses can be found on the paper uploaded to arXiv.
